pipelines:
  branches:
    feature/*:
    - step:
        name: Deploy to AWS
        image: public.ecr.aws/lambda/nodejs:16
        script:
          - export AWS_ACCESS_KEY_ID=$CODERS_AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$CODERS_AWS_SECRET_ACCESS_KEY
          - npm install -g yarn
          - yarn
          - yarn global add codecov
          - yarn format
          - yarn codecov && codecov
          - sam build -b ./build -t ./template.yaml
          - sam package --template-file build/template.yaml --output-template-file packaged.yaml --s3-bucket $CODERS_AWS_BUCKET
          - sam deploy --template-file packaged.yaml --capabilities CAPABILITY_IAM --stack-name chron